ARG VERSION
FROM pixelfed:$VERSION

ENV DEBIAN_FRONTEND=noninteractive

RUN  apt install -y \
    nginx \
    nginx-common \
  && apt clean \
  && apt autoremove -y

COPY default.conf /etc/nginx/sites-available/default
COPY entrypoint.sh-nginx /entrypoint.sh

WORKDIR /usr/share/webapps/pixelfed

EXPOSE 80

ENTRYPOINT [ "/entrypoint.sh" ]
